### ISSUE TITLE
build_pptx and build_thumbnail build to 4:3 ratio always

### ISSUE THREAD

**Issue by mattansb** [jhelvy/renderthis#15]
These function seem to ignore the actual aspect ratio of the xaringan (html) slides.

**Comment by jhelvy** [comment]
Yup, this is a problem. I'll see if I can fix this.

**Comment by jhelvy** [comment]
This should now be fixed for `build_png()` (I depreciated `build_thumbnail()`). 

The aspect ratio is still off for pptx output types though.

**Comment by jhelvy** [comment]
This is now fixed with a somewhat hacky approach, but it appears to work. For now it only supports the default 4:3 ratio and 16:9.

**Comment by mattansb** [comment]
Thanks!
