### ISSUE TITLE
build_pdf onlyprinting the first slide?

### ISSUE THREAD

**Issue by giabaio** [jhelvy/renderthis#24]
It may well be me messing up something obvious, but I seem to have a problem in printing my slides with `build_pdf`. The `Rmd` file compiles just fine onto html and is published [here](http://www.statistica.it/gianluca/slides/bcea).

When I try to print it to pdf using `build_pdf` I get a weird result that the process seems to work fine, but only the title page and the first part of the first slide are printed. The resulting pdf does have 11 pages (that's as many as there are full slides on the html file), but basically all pages from 2 to 11 show the same (half of what should be slide 2).

I've installed the current version of `xaringanBuilder` from this repo and I think I have all the relevant pre-requisites. I'm on Ubuntu 20.04 (but this should not be a problem) and of course I do have Google Chrome installed.

Any obvious point I'm missing?
Thanks!

**Comment by jhelvy** [comment]
I can't reproduce the error. I ran this code and got a PDF that looks correct:

```r
xaringanBuilder::build_pdf("http://www.statistica.it/gianluca/slides/bcea/index.html")
```

**Comment by giabaio** [comment]
Does OK on my computer too **now**. I am not sure what was going on. I did reboot after sending the message (and I was on a relatively new installation, so maybe reboot was needed for something to kick in and start working?...).
Thanks anyway!
