### ISSUE TITLE
Provide user control over overwriting behavior

### ISSUE THREAD

**Issue by gadenbuie** [jhelvy/renderthis#30]
I would appreciate it if there were a way to have a little more control over the overwriting behavior of the `build_*()` functions. Currently, files are overwritten without any warning or confirmation and there's no way to turn that feature off. This always makes me nervous, especially when it's possible to call a `build_*()` function from the wrong directory and create unexpected files that unintentionally overwrite files in the wrong location.

It'd be good to at minimum have a way to set `overwrite = FALSE` even if the default value were `TRUE` for ergonomic reasons.

**Comment by jhelvy** [comment]
I thought about this but wasn't sure what would be a good set of default behaviors and optional behaviors. I think there are two questions to address here:

1. Should the default build behavior be to overwrite any existing output file with the same name, or should that be optional and the default be to build a new file with a number attached to the output name. For example, if `output_file = "test.pdf"` and `"test.pdf"` already exists, it will save the pdf as `"test (1).pdf"`. We could add an optional `overwrite` argument to support this, but which should be default is the question. 
2. Should the default behavior be different for _intermediate_ outputs? I had thought about saving all intermediate outputs as temporary files and only saving the final desired output to file. This could also maybe be turned on or off with another optional argument to save all intermediate outputs, maybe `save_intermediate_outputs = FALSE` (that's a long name, I know). 

Any thoughts on these?

**Comment by gadenbuie** [comment]
OTOH, the only intermediates that are kept and/or reused are `html` and `pdf`, right? IIUC, the build hierarchy looks like this now

```
    # Rmd
    #  |
    #  |--> social (png)
    #  |
    #  |--> html
    #        |
    #        |--> pdf
    #              |
    #              |--> png
    #              |
    #              |--> gif
    #              |
    #              |--> mp4
    #              |
    #              |--> pptx
```

since we don't need the `png` files to be on disk to render `gif` outputs — they're read from the `pdf` instead. If this is right, then it's really a question of keeping the `html` (we should) and/or the `pdf` (don't _need_ to). 

I think that the further to the right one moves the less likely they care about intermediates. So it makes sense to me to render slides to a temp pdf if the user wanted an `mp4` output. A second indication is whether or not the output is being saved into the original directory. A user who calls `build_mp4()` and saves the `mp4` file somewhere else on their computer is much less likely to want there to be an extra `pdf` file where the original slides are located.

`build_html()` is the problematic one. There really isn't any getting around needing to run `rmarkdown::render()` in place.

With all of the above, my opinion leans toward switching my argument name recommendation above from `clean_intermediates` to `keep_intermediates`. Then `keep_intermediates = FALSE` by default for anything to the right of `pdf` outputs and `keep_intermediates = TRUE` for `pdf`.

**Comment by jhelvy** [comment]
Okay, I think this breaks down to a few changes:

1. Update the `build_paths()` function to:
    - Be a little smarter and to use the input directory for all outputs (unless the user provides a different output directory). 
    - Use relative paths for `build_html()` and absolute paths for everything else.
    - In the case that the output format is html, make sure that the output directory is the same as the input directory. If the user specifies a different directory, we could maybe throw a warning? Or maybe do nothing and just let it go...my sense is this will be a rare occasion.
2. Introduce a `keep_intermediates` argument for all `build_*()` functions from pdf and later in the build hierarchy, setting the defaults such that `keep_intermediates = FALSE` for anything "right" of pdf and `keep_intermediates = TRUE` for pdf (which just keeps the html).

With these changes, allowing output file overwriting should be fine. I think these will also address issue #29.

The only remaining suggestion here is making the `build_*()` functions smarter to be able to start building from further down in the build hierarchy if intermediate files are up to date. I don't see this issue as being as high on the priority list as the other suggested changes above, so maybe we implement the above changes and come back to it separately? I also don't see too much benefit to building from intermediate files, maybe just decreased computation time, which would only really make a difference in a batch operation. For most purposes, building from scratch is pretty fast, and I'm more confident that all the output files will be up to date.

**Comment by gadenbuie** [comment]
> For most purposes, building from scratch is pretty fast, and I'm more confident that all the output files will be up to date.

I agree, this is definitely lower priority. Also, confidence that an intermediate file is up-to-date wrt to the requested final output starts to break down the more to the right in the graph you are. Maybe a PDF file was created but not with the slides you need, etc. We could be reasonably confident about skipping the `Rmd -> html` step if the `html` is up to date, but that's also a small bit of savings.

**Comment by jhelvy** [comment]
Okay, so the question is how to implement the changes. I've got a few more items in the priority list for next few days, but maybe could tackle it Friday unless you want to give it a shot.
