### ISSUE TITLE
xaringanBuilder requires cli 3.0.0

### ISSUE THREAD

**Issue by howardm** [jhelvy/renderthis#37]
I'm trying to build from an "index.Rmd" file. 

It is:

````
Error: 'format_inline' is not an exported object from 'namespace:cli'

````

I installed chromate successfully.

Any ideas ?

Thanks!

**Comment by gadenbuie** [comment]
Please try installing the latest version of the `cli` package. I didn't realize that `format_inline()` is a newer function introduced in version 3.0.0. I'll check my usage of it and either come up with an alternative or add a version requirement to our `cli` dependency.

**Comment by howardm** [comment]
That worked.

Thanks!

**Comment by gadenbuie** [comment]
Glad to hear it @howardm!

@jhelvy can you please re-open this issue and perhaps change the title to "xaringanBuilder requires cli 3.0.0"? Thank you 😄

**Comment by jhelvy** [comment]
Done!
