### ISSUE TITLE
Can't find Google Chrome when it is installed in Linux

### ISSUE THREAD

**Issue by bshor** [jhelvy/renderthis#39]
Hello,

I'm running the latest versions of R and Rstudio on Arch-derived Garuda Linux. I'm also running the latest version of Google Chrome.

I want to output PDF from my Xaringen slides (I can see the HTML just fine).

But I get the following error:

```
google-chrome` and `chromium-browser` were not found. Try setting the CHROMOTE_CHROME environment variable or adding one of these executables to your PATH.
Error: This function requires a local installation of the Chrome browser. You can also use other browsers based on Chromium, such as Chromium itself, Edge, Vivaldi, Brave, or Opera.
```

I see how to set the environmental variable, but I'm getting an error from the Fish shell:

```
╰─λ Sys.setenv(CHROMOTE_CHROME = "/usr/bin/google-chrome-stable")
fish: Command substitutions not allowed
Sys.setenv(CHROMOTE_CHROME = "/usr/bin/google-chrome-stable")

```

**Comment by gadenbuie** [comment]
@bshor Run that code in your R console before building PDFs

```r
Sys.setenv(CHROMOTE_CHROME = "/usr/bin/google-chrome-stable")
```

or open `~/.Renviron` and add a line like this

```
CHROMOTE_CHROME="/usr/bin/google-chrome-stable"
```

**Comment by bshor** [comment]
Thank you! Setting it in ~/.Renviron worked perfectly. Guess I don't have a full handle on Linux environmental variables. I'm getting some other error, but this part is fixed, thanks!
