### ISSUE TITLE
Error when converting html file to powerpoint using xaringanBuilder

### ISSUE THREAD

**Issue by JEFFGAFNA16** [jhelvy/renderthis#41]
Am trying to convert my html file into powerpoint presentation but I get this error.
Here is my code and error

library(xaringanBuilder)
build_pptx("Rmarkdown/My_first_paper_presentation_final.html", output_file = "Rmarkdown/Pow/First_paper.pptx", slides = "all", complex_slides = TRUE, delay = 1)

Error: 'format_inline' is not an exported object from 'namespace:cli'

**Comment by gadenbuie** [comment]
Please update to the latest version of xaringanBuilder, which will ensure you also have the latest version of the cli package. This was reported in #37 and fixed in #38.

```r
remotes::install_github("jhelvy/xaringanBuilder")
```
