### ISSUE TITLE
complex_slides getting stuck?

### ISSUE THREAD

**Issue by giabaio** [jhelvy/renderthis#45]
Hi all,
I may be doing something wrong, but I seem to have a slight issue with `complex_slides`. All seems to work OK when I set it to `FALSE`. However, when I try to set it to `TRUE` because my presentation contains `panelsets`, the resulting pdf gets "stuck" on one of the first few slides. It creates many pdf pages, but they are all the same as the last "valid" one.

For example, I have [this](https://gianluca.statistica.it/slides/armitage/seminar/#1) presentation, which contains `panelsets`. If I run
```
xaringanBuilder::build_pdf(
   "https://gianluca.statistica.it/slides/armitage/seminar/index.html",
   complex_slides = TRUE,output_file = "test.pdf"
)
```
the resulting pdf does the title slide and the first slide OK, but then every other slide is a replica of slide 2.

If I don't add the options about `complex_slides` or `partial_slides`, then the pdf is compiled OK with all the pages (although, the `panelsets` of course don't work well as only the first panel is included...).

I do have Chrome installed and updated (though it's not my default browser) --- so am I missing something obvious? Or can people not replicate my problem and manage to print the pdf of the slides above OK?

Thanks
Gianluca

**Comment by jhelvy** [comment]
I can produce the same result of getting stuck on slide 2 with your example. We'll see if we can get to the bottom of this.

**Comment by giabaio** [comment]
Thank you, @jhelvy!

**Comment by gadenbuie** [comment]
Can you share the slide source? Could you also try removing the footer in the second slide and then calling `build_pdf()` on the local copy without the footer (with `complex_slides = TRUE`)?

**Comment by giabaio** [comment]
I can share the source code --- what's the best way to do it? Should it stick it somewhere for you to download? 
Also: I have tried your suggestion (removing the footer), but nothing changes. In fact, the point at which the pdf gets stuck seems to be the first time that there's a "pause" --- something like
```
Some code here

--

Some code after the pause
```

Any use?

**Comment by gadenbuie** [comment]
> Also: I have tried your suggestion (removing the footer), but nothing changes.

Bummer 😞 

> I can share the source code --- what's the best way to do it? Should it stick it somewhere for you to download?

If you don't have the source code on GitHub, you could put the `.Rmd` file (and any supporting files except for images or big files) into a zip and drop it in a comment here (I think that would work).

**Comment by giabaio** [comment]
Source code available [here](https://github.com/giabaio/one-year-of-covid)

**Comment by gadenbuie** [comment]
Thanks for the source code @giabaio. Your slides look great! But there's _quite a lot_ going on in them. I spent a few hours last evening trying to extract a smaller reprex, but there's so much going on in the slides that it's hard to find the part that's interacting with the slide printing.

But! Just now as I'm writing this, I realized the problem. It's these lines in `assets/ucl-stats.css`:

```css
/* This allows incremental slides to be printed to pdf using
 * see: https://stackoverflow.com/questions/56373198/get-xaringan-incremental-animations-to-print-to-pdf
*/
@media print {
  .has-continuation {
    display: block!important;
  }
}
```

What happens is that once we hit a slide with a continuation, the `display:block !important` ensures that it's visible. So the slides _are_ changing, it's just that the partial slide we walked through is visible in front of any other slides. If I remove those lines, I get the following PDF output...

![image](https://user-images.githubusercontent.com/5420529/148565756-6f17ac6d-8120-4460-8f28-df45fb7c8a2e.png)

_Edit: note those slides above aren't exactly the same as the originals since I deleted lots of stuff in trying to get down to a reprex._

**Comment by jhelvy** [comment]
I figured this was one for @gadenbuie - way to go in getting to the bottom of this!

**Comment by giabaio** [comment]
Ah - that's brilliant! Thank you so much, @gadenbuie! I've spent *a lot* of time fiddling with css (my wife keeps saying I should get a life instead... :-) ), but I'm very much an amateur (and I'm sure the css file could be streamlined and made *much* more efficient!).

But this is exactly what I needed -- thank you! :pray:

**Comment by gadenbuie** [comment]
You're welcome!

> I've spent _a lot_ of time fiddling with css (my wife keeps saying I should get a life instead... :-) )

Just tell her it's not _fiddling_ — you're [slidecrafting](https://twitter.com/grrrck/status/1159087961931169795)!

**Comment by giabaio** [comment]
:laughing:
