### ISSUE TITLE
Deprecate `build_*()` functions

### ISSUE THREAD

**Issue by gadenbuie** [jhelvy/renderthis#51]
`renderthis` currently is a clean break from the `build_*` naming convention of xaringanBuilder. We probably want to instead gracefully deprecate the function names ([lifecycle stages: deprecated](https://lifecycle.r-lib.org/articles/stages.html#deprecated)).

This will also help us avoid internal errors if we happen to mention a `build_*` function somewhere that we haven't migrated yet.

**Comment by gadenbuie** [comment]
(FYI I'm working on getting this started)

**Comment by jhelvy** [comment]
I think this is done now?

**Comment by gadenbuie** [comment]
Fixed in #52
