### ISSUE TITLE
Issue with google font

### ISSUE THREAD

**Issue by bbitarello** [jhelvy/renderthis#68]
Hello, I am trying to use renderthis::to_pdf but I am getting an error related to a google font I am using. I have searched online but have no idea how to fix this. Any help appreciated. Thank you

I am using Rstudio in a Mac OS Monterrey. This is a slide deck made in R markdown using the xaringan package.

`> renderthis::to_pdf("07_TheNormalDistribution_II.Rmd")
✔ Rendering 07_TheNormalDistribution_II.Rmd into 07_TheNormalDistribution_II.htm…
✖ Rendering 07_TheNormalDistribution_II.html into 07_TheNormalDistribution_II.pd…
Error in force(expr) : 
  Failed to generate output. Reason: Failed to open https://fonts.googleapis.com/css?family=EB+Garamond:300,300i&display=swap (HTTP status code: 400)`

**Comment by jhelvy** [comment]
Perhaps you have a wrong url for the fonts? If I go to the url for the fonts you have set, I get a 404 error: 

https://fonts.googleapis.com/css?family=EB+Garamond:300,300i&display=swap

**Comment by bbitarello** [comment]
Yes, you are correct. I had just figured this out. I will close this. Thanks
