### ISSUE TITLE
Missing plots due to messed up margins in PDF but not HTML

### ISSUE THREAD

**Issue by bshor** [jhelvy/renderthis#69]
I am still having problems with plots extending past the margins and then not being included in PDF output.

@gadenbuie suggested including a red outline to see the problem. Well, this red outline shows fine on the HTML, but totally past the margins in the PDF (produced using to_pdf in renderthis).

HTML:

![image](https://user-images.githubusercontent.com/468070/203627287-f78a2c2d-9da9-4b11-8be2-a20ba5b32bec.png)

PDF:

![image](https://user-images.githubusercontent.com/468070/203627394-0fbc2f03-ec50-40a7-8106-b4a309e7871c.png)

Any idea about what I shoudl do?

**Comment by jhelvy** [comment]
Same as #44

**Comment by bshor** [comment]
Right but look at how much the plot shifted. It's not an issue of margins, as the margins are rather tight around the plot itself, and there's even some separation between the red line and the edge of the slide.

In any case, perhaps some kind of simple shrink would do the trick. Do you have suggestions to shrink plots like this, both from PNGs and code-generated plots?

**Comment by bshor** [comment]
Wait ... I figured it out. The plot was fine, but not the figure caption, which extended below the slide. So setting out.width to be smaller did the trick, as did eliminating the caption. Thanks for the help and pointers!
