### ISSUE TITLE
Add social media share card 

### ISSUE THREAD

**Issue by jhelvy** [jhelvy/renderthis#7]
Per @gadenbuie's [recommendation](https://twitter.com/grrrck/status/1359002774055366658), add social media card print output - like thumbnail but with a better aspect ratio for sharing on social media:

https://www.garrickadenbuie.com/blog/sharing-xaringan-slides/#the-perfect-share-image-ratio

**Comment by jhelvy** [comment]
Added with v0.0.4

**Comment by gadenbuie** [comment]
I'm glad this made it in here! It already came in handy just yesterday.

One comment from my testing: if the user gives an output filename, the function shouldn't modify that name. In other words, it should use `<input_basename>_social.png` only if output path is `NULL` and we're choosing the output filename based on the input.

**Comment by jhelvy** [comment]
Good catch - should be fixed now with [a875650](https://github.com/jhelvy/xaringanBuilder/commit/a87565078565de26c573511649517a36370710e9)
