### ISSUE TITLE
Error in sink(con, split = debug) : sink stack is full

### ISSUE THREAD

**Issue by rmharp** [jhelvy/renderthis#72]
I was only able to run this once and now I continue to get the same error, even after restarting R and clearing output. I've also tried the following with no progress being made:
> sink() 
Warning message:
In sink() : no sink to remove

**Comment by rmharp** [comment]
For context, here is what I am trying to run, renderthis::to_pdf("WeeklyMeeting1.Rmd").

**Comment by gadenbuie** [comment]
Unfortunately, what's inside the document is likely to be very relevant to the error. If renderthis is the source of the error, you should be able to reproduce the problem with a minimal Rmd file. But without a runnable example that reproduces the issue, I'm afraid we won't be able to help much.

**Comment by gadenbuie** [comment]
Oh I'm now seeing the connection. I think you provided the source for `WeeklyMeeting1.Rmd` over here: https://github.com/gadenbuie/xaringanExtra/issues/187#issuecomment-1750769318

If that's the case, then it looks like you're calling `renderthis::to_pdf()` inside the `.Rmd` document that you're trying to render. That's going to lead to a circular dependency where each render kicks off a subprocess to try to render the slides again. Can you try removing that line to see if the problem persists?

**Comment by rmharp** [comment]
Yes, I was doing that and see how it could cause an issue. However, even when calling this in an entirely different. rmd file the same error occurs. For context, this was my error in an entirely different file: 
ℹ Rendering WeeklyMeeting1.Rmd into WeeklyMeeting1.html
Quitting from lines 16-36 [unnamed-chunk-2] (WeeklyMeeting1.Rmd)
✖ Rendering WeeklyMeeting1.Rmd into WeeklyMeeting1.html ... failed
Error in sink(con, split = debug) : sink stack is full
Which matches my original error. When trying sink() to close the sink stack I am told:
> sink()
Warning message:
In sink() : no sink to remove

**Comment by gadenbuie** [comment]
Interesting. But I don't expect `renderthis::to_pdf()` to work when called from inside a running knitr process. It's not something we anticipated in the design of renderthis and I'd be  surprised if it works. We could also block `renderthis::to_*()` from being called inside a running knitr process, but that also seems a bit too aggressive unless there's a clear indication that it would never work in practice.

At this point, I'd say: it was worth a try! But you're probably better off calling `renderthis::to_*()` outside of any `.Rmd` file.

**Comment by rmharp** [comment]
Setting my working directory then running in terminal fixed the issue! Thank you and for future reference it does seem to work when run directly in a .rmd although the issue I've discussed above can occur in certain files (but not all for some reason).
