### ISSUE TITLE
Folder usage returns folder does not exist

### ISSUE THREAD

**Issue by g4challenge** [jhelvy/renderthis#8]
When running the command:
` build_pdf("R/my_slides.Rmd", complex_slides=TRUE)`

The error occurs:
The directory "R" does not exist

This feedback is incorrect and there is no further feedback to this...

**Comment by jhelvy** [comment]
Thanks for noting this - I see the bug, fixing it now.

**Comment by jhelvy** [comment]
Okay, I believe this should be fixed now with [this commit](https://github.com/jhelvy/xaringanBuilder/tree/a379172651f2b347401ed7c84ff7f251acf0bd29)

Can you reinstall from github and see if you're still getting the error?
