### ISSUE TITLE
renderthis::to_pdf .html file 404 error

### ISSUE THREAD

**Issue by dmontecino** [jhelvy/renderthis#82]
Hi, @jhelvy . Thank you so much for the package! Two monthis ago I was running this line of code without problems. Now I get this error. Any guidance you could kindly provide? 

`> renderthis::to_pdf("docs/es/Dictionary.es.html")
✖ Rendering docs/es/Dictionary.es.html into docs/es/Dictionary.es.pdf ... failed
Error in force(expr) : 
  Failed to generate output. Reason: Failed to open http://127.0.0.1:6886/favicon.ico (HTTP status code: 404)`

Many thanks in advance

**Comment by gadenbuie** [comment]
Are you using the latest version of the servr package?

**Comment by dmontecino** [comment]
@gadenbuie works like a charm now. Thanks ! I did update the renderthis package and that requested updating a bunch of other packages. I updated them all. but that did not solve the problem. installing the specific package servr again did (I dont know if this is something that could be improved). Thanks!

**Comment by gadenbuie** [comment]
I suppose we could require the latest version of servr in renderthis. We already require pagedown, which we only use for printing to PDF in `to_pdf()`
