### ISSUE TITLE
Error in magick_image_readpath(path, density, depth, strip, defines)

### ISSUE THREAD

**Issue by liutiming** [jhelvy/renderthis#9]
Thanks so much for this awesome package!

command and output:
```
> build_pptx("test.Rmd")
v Building test.html from test....
v Building test.pdf from test.h...
[2021-02-12 18:27:00] [error] handle_read_frame error: asio.system:10054 (An existing connection was forcibly closed by the remote host.)
v Building test.pptx from test....
Error in magick_image_readpath(path, density, depth, strip, defines) : 
  rsession.exe: FailedToExecuteCommand `"gs" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72"  "-sOutputFile=C:/Users/timing/AppData/Local/Temp/Rtmpo36Yun/magick-tetLqr9tDeXlqYGf9Fen6MYHRjIDzts1%d" "-fC:/Users/timing/AppData/Local/Temp/Rtmpo36Yun/magick-5fAO1_6eb5-YjUqFdClwzzvkRMrL1COC" "-fC:/Users/timing/AppData/Local/Temp/Rtmpo36Yun/magick-08ou7S3AZwo3k5y2OBobsrzHMRlZeaJP"' (The system cannot find the file specified.
) @ error/delegate.c/ExternalDelegateCommand/457
```

R markdown file:
```
---
title: "Presentation Ninja"
subtitle: "⚔<br/>with xaringan"
author: "Yihui Xie"
institute: "RStudio, PBC"
date: "2016/12/12 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

background-image: url(https://upload.wikimedia.org/wikipedia/commons/b/be/Sharingan_triple.svg)
```

```
sessionInfo:

R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    
system code page: 936

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] xaringanBuilder_0.0.4.9000

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6        rstudioapi_0.11   knitr_1.31       
 [4] servr_0.21        xml2_1.3.2        magrittr_2.0.1   
 [7] uuid_0.1-4        R6_2.5.0          rlang_0.4.10     
[10] stringr_1.4.0     tools_4.0.3       websocket_1.3.1  
[13] packrat_0.5.0     xfun_0.20         xaringan_0.19.2  
[16] cli_2.3.0         htmltools_0.5.1.1 yaml_2.2.1       
[19] digest_0.6.27     assertthat_0.2.1  processx_3.4.5   
[22] zip_2.1.1         later_1.1.0.1     officer_0.3.16   
[25] ps_1.5.0          promises_1.1.1    fs_1.5.0         
[28] mime_0.9          glue_1.4.2        evaluate_0.14    
[31] rmarkdown_2.6.6   stringi_1.5.3     compiler_4.0.3   
[34] magick_2.6.0      jsonlite_1.7.2    httpuv_1.5.5     
[37] pagedown_0.13    
```

**Comment by jhelvy** [comment]
I just ran your example and was not able to reproduce the error. My output: 

```{r}
> library(xaringanBuilder)
> 
> build_pptx("test.Rmd")
✓ Building test.html from test.Rmd ... done
✓ Building test.pdf from test.html ... done
✓ Building test.pptx from test.pdf ... done
```

Is Chrome installed on your machine? You need Chrome for some of the output types. 

Looks like it failed when making the pdf from the html file. Can you see if the html was built?

**Comment by liutiming** [comment]
Thanks! @jhelvy 

yes the html is built. attached

Could it be a problem with Windows? Yes Chrome is installed.

[test.zip](https://github.com/jhelvy/xaringanBuilder/files/5973884/test.zip)

**Comment by liutiming** [comment]
Also, I realised that there may be a use case of using the package on a cluster. Do you think chromium will work? I am not sure if I can install chrome without sudo...

**Comment by jhelvy** [comment]
Okay it looks like your html built correctly. I'm still not able to reproduce the error you're getting though. Did you install the latest version from Github? I patched a file path error just yesterday. 

I haven't tried it yet on a cluster, but if Chrome isn't installed some features probably won't work.

**Comment by liutiming** [comment]
Yup I installed today so it should be the latest version :)

**Comment by jhelvy** [comment]
Can you try building the intermediate files separately to narrow down the error? 
It looks like it's in building the pptx from the pdf, so maybe try just that step:

```
build_pptx("test.pdf")
```

**Comment by liutiming** [comment]
Yes this step produced the error:
```
> build_pptx("test.pdf")
v Building test.pptx from test.pdf ... done
Error in magick_image_readpath(path, density, depth, strip, defines) : 
  rsession.exe: FailedToExecuteCommand `"gs" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72"  "-sOutputFile=C:/Users/timing/AppData/Local/Temp/Rtmpo36Yun/magick-QgpXrcwcHzv7DOdjD_cgGIoXGe9e9RLV%d" "-fC:/Users/timing/AppData/Local/Temp/Rtmpo36Yun/magick-RAwu2BDkpzaoDyWZLmQlLruZgTPoHJSC" "-fC:/Users/timing/AppData/Local/Temp/Rtmpo36Yun/magick-rj-F_vpmtyBf4IQFmwinbVyzdMYLHiTH"' (The system cannot find the file specified.
) @ error/delegate.c/ExternalDelegateCommand/457
```

**Comment by liutiming** [comment]
wondering how to check if magick is on my computer?

**Comment by jhelvy** [comment]
I would imagine you'd get other errors if you tried to use other functions from the [magick package](https://cran.r-project.org/web/packages/magick/vignettes/intro.html). Could you try something like `image_read()` to see if you can use magick without errors?

**Comment by liutiming** [comment]
strangely this does not produce errors...
![image](https://user-images.githubusercontent.com/39947942/107824695-cfd14180-6d79-11eb-8c10-427d6fc8c594.png)

**Comment by jhelvy** [comment]
Alright, so you've got magick installed and can use it. 

The error seems to be related to [this issue](https://github.com/ropensci/magick/issues/168), which apparently was fixed with magick 2.5.1. But you're running 2.6.0, so it should work.

**Comment by jhelvy** [comment]
do you have pdftools installed? See [this SO post](https://stackoverflow.com/questions/48834749/error-using-magick-r-to-import-pdf)

**Comment by liutiming** [comment]
Problem solved after installing GhostScript 64 bits. Thank you so much!

**Comment by jhelvy** [comment]
Hey, I just added a check to throw an error message if Chrome isn't installed. Since you were working on a system without Chrome, could you try and build a pdf to see if the error message is working?

**Comment by liutiming** [comment]
just saw! I have added that to my to-dos and will update when i do that
